export type FlattenedTrack = {
  id: string;
  title: string | null;
  csvTitle: string | null;
  workspace: string | null;
  workspaceId: string | null;
  status: string | null;
  createdAt: string | null;
  duration: number | null;
  type: string | null;
  isStem: boolean | null;
  wavPath: string | null;
  txtPath: string | null;
  mp3Path: string | null;
  imagePath: string | null;
  thumbPath: string | null;
  videoPath: string | null;
  waveformPath: string | null;
  path: string | null;
  traktorPath: string | null;
  hasWav: boolean;
  hasTxt: boolean;
  hasMp3: boolean;
  hasImage: boolean;
  hasThumb: boolean;
  hasVideo: boolean;
  hasWaveform: boolean;
  isExported: boolean;
  importedAt: string;
  processedAt: string | null;
  analyzedAt: string | null;
  exportedAt: string | null;
  artist: string | null;
  year: number | null;
  prompt: string | null;
  lyrics: string | null;
  tags: string | null;
  displayTags: string | null;
  modelName: string | null;
  modelVersion: string | null;
  task: string | null;
  isRemix: boolean | null;
  isPublic: boolean | null;
  isExplicit: boolean | null;
  musicalKey: string | null;
  keySource: 'metadata' | 'related' | 'traktor' | 'aubio' | 'none' | null;
  bpm: number | null;
  bpmSource: 'metadata' | 'related' | 'traktor' | 'aubio' | 'none' | null;
  categories: string[];
  metadata?: Record<string, unknown>;
  updatedAt: string;
};

export type WaveformData = {
  v: 1;
  sampleRate: number;
  fftSize: number;
  pointCount: number;
  duration: number;
  low: number[];
  mid: number[];
  high: number[];
};

export type LibraryPlaylist = {
  id: string;
  name: string;
  groupKey: string;
  groupValue: string;
  trackIds: string[];
  trackCount: number;
  availableTrackCount: number;
  path: string | null;
  exportPath: string | null;
  updatedAt: string;
};

export type LibraryData = {
  version: number;
  updatedAt: string;
  steps: Record<string, string>;
  tracks: FlattenedTrack[];
  playlists: LibraryPlaylist[];
};
