import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'TOKUDU SUNO',
  description: 'A hosted library of TOKUDU music tracks generated by Suno (2025/2026)',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark">
      <body className="font-sans text-gray-100 antialiased bg-[#0a0a0f]">{children}</body>
    </html>
  );
}
